### ISSUE TITLE
Inconsistent naming of Counter metric

### ISSUE THREAD

**Issue by smrutilal2** [ultrabrew/metrics#30]
### Current aggregations:
* counter: _sum_
* timer: _count_, _sum_, _min_, _max_
* guage: _count_, _sum_, _min_, _max_, _lastValue_

The count aggregation field from a counter metric is reported as _sum_ where as from a timer or guage, it's reported as _count_. This is very confusing while modeling the instrumentation for an application.

It's also difficult to change the type of a metric. For example, if developer wants to change a counter metric to timer or vice-versa, the name of the count aggregation would change. This would break the existing queries.

### Suggestion: 
change the aggregation field name  of the Counter metric to _count_.

## Note:
We need to be little careful as this would break the existing monitoring. May be we have to do a major version upgrade. to roll out this change.

**Comment by mmannerm** [comment]
Can you still increment the counter more than by 1 or decrement it? Count is count of samples, while value or sum is more appropriate for rates, etc. We dropped the count though from Counter so we can’t do average change etc, so maybe it does not matter. If we still allow decrements of any kind OR increments by more than 1, then count is not correct term. Value or sum are better terms

**Comment by smrutilal2** [comment]
As far as the core library is concerned, it's just a counter. Reporter can reset the value and report it as rate. It doesn't matter if you increment by one or multiple. End of the day, it's keeping the count of an entity.

It's also in a way breaks one of the key claim of Ultrabrew which is, if you have a timer metric you don't need another counter metric to track the count. 

Say, you have a Counter metric that reports the count as _sum_ for the http request to track your rps. Afterwards, if you want to track the latency and change the type to Timer, the count will be reported as _count_. This is inconsistent.

**Comment by smrutilal2** [comment]
I agree to you @mmannerm. When I thought more about it, I realized that the aggregation `count` in a Timer is fundamentally different from the `sum` in a Counter. The former keeps track of the number of samples recorded where as the later is the sum of all the samples. 

Closing this issue.
